In [1]:
import torch
from nlrl import NeuralLogicRuleLayer

i, j = 2, 3

GR = torch.empty((i, j)).uniform_(-0.5, 0.5)
GR

tensor([[ 0.4299, -0.1861,  0.2887],
        [ 0.3341, -0.2337, -0.1453]])

In [2]:
x = torch.empty((i, j)).uniform_(0, 1)
log_x = torch.log(x + 1e-6)
print("log_x.shape      ", log_x.shape)
print("log_x            ", log_x)


log_x.shape       torch.Size([2, 3])
log_x             tensor([[-1.5449, -0.0232, -0.9403],
        [-0.2034, -0.7520, -5.3800]])


In [3]:
sGR = torch.sigmoid(GR)
print("sGR.shape        ", sGR.shape)
print("sGR              ", sGR)


sGR.shape         torch.Size([2, 3])
sGR               tensor([[0.6058, 0.4536, 0.5717],
        [0.5828, 0.4419, 0.4637]])


In [4]:
GRlog_x = (torch.sigmoid(GR) * log_x).sum(dim=-2)
print("GRlog_x.shape ", GRlog_x.shape)
print("GRlog_x      ", GRlog_x)



GRlog_x.shape  torch.Size([3])
GRlog_x       tensor([-1.0545, -0.3428, -3.0324])


In [5]:
exp_GRlog_x = torch.exp(GRlog_x)
print("exp_GRlog_x.shape ", exp_GRlog_x.shape)
print("exp_GRlog_x      ", exp_GRlog_x)



exp_GRlog_x.shape  torch.Size([3])
exp_GRlog_x       tensor([0.3484, 0.7098, 0.0482])


In [6]:
print("GR[0]       ", GR[0])
print("x[:, 0]     ", x[:, 0])
torch.pow(x[0, :] + 1e-6, torch.sigmoid(GR[0])) * torch.pow(
    x[1, :] + 1e-6, torch.sigmoid(GR[1])
)

GR[0]        tensor([ 0.4299, -0.1861,  0.2887])
x[:, 0]      tensor([0.2133, 0.8160])


tensor([0.3484, 0.7098, 0.0482])

In [7]:
layer = NeuralLogicRuleLayer(i, j)
layer.GR = torch.nn.Parameter(GR)

print(layer.conjunction(x))

tensor([0.3484, 0.7098, 0.0482], grad_fn=<ExpBackward0>)
